// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZWy2lUKv6VePcq3BgGaKDLaZ7PJ4hP5w',
    appId: '1:39002629513:web:f1f9421bf885050f07ed58',
    messagingSenderId: '39002629513',
    projectId: 'dullany-app',
    authDomain: 'dullany-app.firebaseapp.com',
    storageBucket: 'dullany-app.firebasestorage.app',
    measurementId: 'G-XBN3P3NDVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfF4788VRK2-YnHqfwZQ0GIdbwx9jJ9w',
    appId: '1:39002629513:android:ec653568c5678c4107ed58',
    messagingSenderId: '39002629513',
    projectId: 'dullany-app',
    storageBucket: 'dullany-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1HtL9PEokjsHm84srz91OuPdMW-CG5FA',
    appId: '1:39002629513:ios:9ad3eb8bfdd27a3b07ed58',
    messagingSenderId: '39002629513',
    projectId: 'dullany-app',
    storageBucket: 'dullany-app.firebasestorage.app',
    iosBundleId: 'com.example.dullany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1HtL9PEokjsHm84srz91OuPdMW-CG5FA',
    appId: '1:39002629513:ios:9ad3eb8bfdd27a3b07ed58',
    messagingSenderId: '39002629513',
    projectId: 'dullany-app',
    storageBucket: 'dullany-app.firebasestorage.app',
    iosBundleId: 'com.example.dullany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZWy2lUKv6VePcq3BgGaKDLaZ7PJ4hP5w',
    appId: '1:39002629513:web:54d7f729cd1ccbc107ed58',
    messagingSenderId: '39002629513',
    projectId: 'dullany-app',
    authDomain: 'dullany-app.firebaseapp.com',
    storageBucket: 'dullany-app.firebasestorage.app',
    measurementId: 'G-LM15LZR9VC',
  );
}
